config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    member do
      patch :complete
    end
  end
  root 'tasks#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  enum priority: [:high, :medium, :low]

  validates :title,
            :presence => {message: "Task can't be blank." },
            :length => { in: 4..60, message: 'Task must be more than 4 and less than 60 characters.' }

  def priority= value
    if value.kind_of?(String) and value.to_i.to_s == value
      super value.to_i
    else
      super value
    end
  end

  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def check_user
    unless current_user
      redirect_to new_user_session_path, notice: 'You must be logged in to access this section'
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]
  before_filter :check_user, only: [:show, :edit]

  def index
    if user_signed_in?
      @search = Task.search(params[:q])
      @tasks = @search.result.where(user_id: current_user.id).order('created_at DESC')
    end
  end

  def new
    unless current_user
      redirect_to new_user_session_path, notice: 'You must be logged in to access this section'
    else
      @task = current_user.tasks.build
    end
  end

  def show
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
     redirect_to root_path
    else
     render 'new'
    end
  end

  def update
    if @task.update(task_params)
     redirect_to root_path
    else
     render 'edit'
    end
  end

  def destroy
    @task.destroy
  end

  def complete
    @task = Task.find(params[:id])
    @task.update_attribute(:completed_at, Time.now)
    redirect_to root_path, notice: 'Task successfully completed!'
  end

  private

  def task_params
    params.require(:task).permit(:title, :priority, :deadline, :started_at)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo list</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
</head>
<body>
  <nav class='navbar navbar-default'>
    <div class='container'>
     <div class='navbar-header'>
      <%= link_to 'Todolist', root_path, class: 'navbar-brand' %>
     </div>
      <ul class='nav navbar-nav'>
       <li><%= link_to 'Sign Up', new_user_registration_path %></li>
       <% if current_user.present? %>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
         <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
      <p class='navbar-text'>Logged in as <%= current_user.email %></p>
      <ul class='nav navbar-nav navbar-link navbar-right'>
        <li><%= link_to 'New Task', new_task_path %></li>
        </ul>
      <% end %>
    </div>
  </nav>
  <p class='notice', align='center'><%= notice %></p>
  <p class='alert', align='center'><%= alert %></p>
  <div class='container'>
  <%= yield %>
</body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.text_field :title, :placeholder => 'Insert task' %>
  <%= select(:task, :priority,  [['High', 0], ['Medium', 1], ['Low', 2]], {:prompt => 'Select priority'})%>
  <br><br>Select Start date    <%= f.date_select :started_at %>
  <br><br>Select Deadline date <%= f.date_select :deadline %>
  <br><br><%= link_to 'Back', root_path, :class => 'btn btn-primary' %>
  <%= f.submit 'Create task', :class => 'btn btn-success' %>
<% end %>

app/views/tasks/_static_landing_page.html.erb
<div class='jumbotron'>
  <h2>Welcome to your own Todolist!</h2>
  <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' %>
  <%= link_to 'Log In', new_user_session_path, class: 'btn btn-primary' %>
</div>

app/views/tasks/edit.html.erb
<div class='jumbotron'>
  <h1>Edit Task</h1>
  <%= render 'form'%>
</div>

app/views/tasks/index.html.erb
<% if user_signed_in? %>
  <div class='col-md-6 col-md-offset-3'>
    <div class='sort'>
      <%= search_form_for @search do |f| %>
        <%= f.label :title_cont, 'Task name contain' %>
        <%= f.text_field :title_cont %>
        <%= f.submit 'search '%>
      <% end %>
        Sort by
        <%= sort_link @search, :started_at, 'Start date'%>
        or
        <%= sort_link @search, :priority, 'Priority'%>
        or
        <%= sort_link @search, :completed_at, 'Status'%>
    </div>
    <% @tasks.each do |task| %>
      <div class='index-wrapper'>
        <% if task.completed? %>
          <div class='row task'>
            <div class='col-md-8'>
              <h2 style='opacity: 0.5;' class='task-title'> <strike><%= task.title %> </strike> </h2>
              <p style='opacity: 0.5;' class='task-sub-title task-desc'> Priority: <%= task.priority %>  </p>
              <p style='opacity: 0.5;' class='time-created-at task-sub-title'> Started in <%= task.started_at.try(:strftime, '%d/%m/%Y') %> </p>
              <p style='opacity: 0.5;' class='task-deadline task-title'> Deadline in <%= task.deadline.try(:strftime, '%d/%m/%Y') %> </p>
              <p style='opacity: 0.5;' class='time-created-at task-sub-title'>Created <%= time_ago_in_words(task.created_at.try(:strftime, '%d/%m/%Y')) %> ago </p>
              <p style='opacity: 0.5;' class='time-created-at task-sub-title'> Completed <%= time_ago_in_words(task.completed_at) %> ago </p>
            </div>
              <div class='col-md-2'>
                <p><%= link_to task, remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %></p>
                  <i class='fa fa-trash fa-lg'></i>
                <% end %>
              </div>
          </div>
        <% else %>
          <div class='row task'>
            <div class='col-md-8'>
              <h2 class='task-title'><%= link_to task.title, task %></h2>
              <p class='task-sub-title task-desc'> Priority: <%= task.priority %> </p>
              <p class='time-created-at task-sub-title'>Started in <%= task.started_at.try(:strftime, '%d/%m/%Y') %></p>
              <p class='task-deadline task-title'> Deadline in <%= task.deadline.try(:strftime, '%d/%m/%Y') %></p>
              <p class='time-created-at task-sub-title'>Created <%= time_ago_in_words(task.created_at.try(:strftime, ' %d/%m/%Y')) %> ago</p>
            </div>
            <div class='col-md-2'>
              <p><%= link_to complete_task_path(task), remote: true,  method: :patch do %></p>
              <i class='fa fa-check fa-lg'></i>
              <% end %>
            </div>
            <div class='col-md-2'>
              <p><%= link_to task, remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %></p>
              <i class='fa fa-trash fa-lg'></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <%= render 'static_landing_page' %>
<% end %>

app/views/tasks/new.html.erb
<div class='jumbotron'>
  <% @task.errors.each_with_index do |msg, i| %>
    <br><%= msg[1] %>
  <% end %>
  <h1>New Task</h1>
  <%= render 'form' %>
</div>

app/views/tasks/show.html.erb
<div class='jumbotron'>
  <h2><%= @task.title %></h2>
  <p> Priority: <%= @task.priority %></p>
  <%= link_to 'Back', root_path, :class => 'btn btn-info' %>
  <%= link_to 'Edit', edit_task_path(@task), :class => 'btn btn-info' %>
</div>